Update build-kernel.yml

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -312,28 +312,65 @@ jobs:
     - name: Make Custom-Anykernel3
       if: env.CHECK_FILE_IS_OK == 'true' && env.USE_CUSTOM_ANYKERNEL3 == 'true'
       run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace
-        if [[ ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} == *'.tar.gz' ]]; then
-            wget -nv -O AnyKernel3.tar.gz ${{ env.CUSTOM_ANYKERNEL3_SOURCE }}
-            mkdir AnyKernel3
-            tar -C AnyKernel3/ -zxvf AnyKernel3.tar.gz
-        elif [[ ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} == *'.tar.xz' ]]; then
-            wget -nv -O AnyKernel3.tar.xz ${{ env.CUSTOM_ANYKERNEL3_SOURCE }}
-            mkdir AnyKernel3
-            tar -C AnyKernel3/ -Jxvf AnyKernel3.tar.xz
-        elif [[ ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} == *'.git' ]]; then
-            git clone ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} -b ${{ env.CUSTOM_ANYKERNEL3_BRANCH }} --depth=1 AnyKernel3
-        else
-            wget -nv -O AnyKernel3.zip ${{ env.CUSTOM_ANYKERNEL3_SOURCE }}
-            mkdir AnyKernel3
-            unzip AnyKernel3.zip -d AnyKernel3/
-        fi
-        cp android-kernel/out/arch/${{ env.KERNEL_ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} AnyKernel3/
-        if [ ${{ env.CHECK_DTBO_IS_OK }} = true ]; then
-            cp android-kernel/out/arch/${{ env.KERNEL_ARCH }}/boot/dtbo.img AnyKernel3/
-        fi
-        rm -rf AnyKernel3/.git* AnyKernel3/README.md
+       cd $GITHUB_WORKSPACE/kernel_workspace
 
+       # Ensure CUSTOM_ANYKERNEL3_SOURCE is defined
+       if [ -z "${{ env.CUSTOM_ANYKERNEL3_SOURCE }}" ]; then
+         echo "Error: CUSTOM_ANYKERNEL3_SOURCE is not defined!"
+         exit 1
+       fi
+
+       # Handle different source formats
+       if [[ ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} == *'.tar.gz' ]]; then
+        wget -nv --tries=3 --timeout=30 -O AnyKernel3.tar.gz ${{ env.CUSTOM_ANYKERNEL3_SOURCE }}
+        if [ $? -ne 0 ] || [ ! -s AnyKernel3.tar.gz ]; then
+            echo "Error: Failed to download or the file is empty (AnyKernel3.tar.gz)!"
+            exit 1
+        fi
+        mkdir AnyKernel3
+        tar -C AnyKernel3/ -zxvf AnyKernel3.tar.gz
+
+       elif [[ ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} == *'.tar.xz' ]]; then
+        wget -nv --tries=3 --timeout=30 -O AnyKernel3.tar.xz ${{ env.CUSTOM_ANYKERNEL3_SOURCE }}
+        if [ $? -ne 0 ] || [ ! -s AnyKernel3.tar.xz ]; then
+            echo "Error: Failed to download or the file is empty (AnyKernel3.tar.xz)!"
+            exit 1
+        fi
+        mkdir AnyKernel3
+        tar -C AnyKernel3/ -Jxvf AnyKernel3.tar.xz
+
+       elif [[ ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} == *'.git' ]]; then
+        git clone ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} -b ${{ env.CUSTOM_ANYKERNEL3_BRANCH }} --depth=1 AnyKernel3
+        if [ $? -ne 0 ]; then
+            echo "Error: Failed to clone the Git repository!"
+            exit 1
+        fi
+
+       else
+        wget -nv --tries=3 --timeout=30 -O AnyKernel3.zip ${{ env.CUSTOM_ANYKERNEL3_SOURCE }}
+        if [ $? -ne 0 ] || [ ! -s AnyKernel3.zip ]; then
+            echo "Error: Failed to download or the file is empty (AnyKernel3.zip)!"
+            exit 1
+        fi
+        mkdir AnyKernel3
+        unzip AnyKernel3.zip -d AnyKernel3/
+        if [ $? -ne 0 ]; then
+            echo "Error: Failed to extract AnyKernel3.zip!"
+            exit 1
+        fi
+       fi
+
+       # Copy kernel files
+       cp android-kernel/out/arch/${{ env.KERNEL_ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} AnyKernel3/
+
+       # Optionally copy dtbo.img
+       if [ "${{ env.CHECK_DTBO_IS_OK }}" = "true" ]; then
+        cp android-kernel/out/arch/${{ env.KERNEL_ARCH }}/boot/dtbo.img AnyKernel3/
+       fi
+
+       # Clean up unnecessary files
+       rm -rf AnyKernel3/.git* AnyKernel3/README.md
+       
     - name: Make boot image
       if: env.HAVE_SOURCE_BOOT_IMAGE == 'true' && env.CHECK_FILE_IS_OK == 'true'
       run: |
