Update build-kernel.yml

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -300,7 +300,23 @@ jobs:
       if: env.CHECK_FILE_IS_OK == 'true' && env.USE_CUSTOM_ANYKERNEL3 != 'true'
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
-        git clone https://github.com/osm0sis/AnyKernel3 --depth=1 AnyKernel3
+
+
+
+        if [[ https://github.com/Jbub5/AnyKernel3 == *'.git' ]]; then
+           git clone https://github.com/Jbub5/AnyKernel3 -b proton --depth=1 AnyKernel3
+else
+           wget -nv --tries=3 --timeout=30 -O AnyKernel3.zip https://github.com/Jbub5/AnyKernel3/archive/refs/heads/proton.zip
+           if [ $? -ne 0 ] || [ ! -s AnyKernel3.zip ]; then
+               echo "Failed to download AnyKernel3.zip or the file is empty!"
+               exit 1
+           fi
+           mkdir AnyKernel3
+           unzip AnyKernel3.zip -d AnyKernel3/
+        fi
+
+
+
         sed -i 's/do.devicecheck=1/do.devicecheck=0/g' AnyKernel3/anykernel.sh
         sed -i 's!BLOCK=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!BLOCK=auto;!g' AnyKernel3/anykernel.sh
         sed -i 's/IS_SLOT_DEVICE=0;/is_slot_device=auto;/g' AnyKernel3/anykernel.sh
